# -*- coding: utf-8 -*-
"""framework_modified.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AcFuYE4QxvKX0NVMIvcLTKiUG_oP2DwV
"""

import torch
import numpy as np
from torch import nn, optim
from .utils import AverageMeter
from tqdm import tqdm
import os
from opennre.model.para_loss import PARALoss
from opennre.framework.f1_metric import F1Metric
import pickle as pk
from functools import partial


class SentenceRE(nn.Module):

    def __init__(self,
                 model,
                 train_loader,
                 val_loader,
                 test_loader,
                 ckpt,
                 max_epoch=100,
                 lr=0.1,
                 weight_decay=1e-5,
                 opt='sgd',
                 add_subject_loss=False,
                 loss_func=PARALoss(),
                 metric=F1Metric()
                 ):

        super().__init__()
        self.metric = metric
        self.add_subject_loss = add_subject_loss
        self.max_epoch = max_epoch
        # Load data
        self.train_loader = train_loader
        self.val_loader = val_loader
        self.test_loader = test_loader

        # Model
        self.model = model
        self.parallel_model = nn.DataParallel(self.model)
        # nn.parallel.DistributedDataParallel(self.model,device_ids=)
        # Criterion
        self.loss_func = loss_func
        self.subject_loss = torch.nn.CrossEntropyLoss()
        # Params and optimizer
        params = self.parameters()
        self.lr = lr
        if opt == 'sgd':
            self.optimizer = optim.SGD(params, lr, weight_decay=weight_decay)
        elif opt == 'adam':
            self.optimizer = optim.Adam(params, lr, weight_decay=weight_decay)
        elif opt == 'adamw':  # Optimizer for BERT
            from transformers import AdamW
            params = list(self.named_parameters())
            no_decay = ['bias', 'LayerNorm.bias', 'LayerNorm.weight']
            grouped_params = [
                {
                    'params': [p for n, p in params if not any(nd in n for nd in no_decay)],
                    'weight_decay': 0.01,
                    'lr': lr,
                    'ori_lr': lr
                },
                {
                    'params': [p for n, p in params if any(nd in n for nd in no_decay)],
                    'weight_decay': 0.0,
                    'lr': lr,
                    'ori_lr': lr
                }
            ]
            self.optimizer = AdamW(grouped_params, correct_bias=False)
        else:
            raise Exception("Invalid optimizer. Must be 'sgd' or 'adam' or 'adamw'.")
        # Cuda
        if torch.cuda.is_available():
            self.cuda()
        # Ckpt
        self.ckpt = ckpt

    def train_model(self, warmup=True, metric='acc'):
        best_metric = 0
        global_step = 0

        for epoch in range(self.max_epoch):
            self.train()
            from tqdm import tqdm
            tqdm = partial(tqdm, position=0, leave=False)
            print("=== Epoch %d train ===" % epoch)
            avg_loss = AverageMeter()
            avg_acc = AverageMeter()
            t = tqdm(self.train_loader, leave=False)

            # self.metric.reset()
            data_idx = 0
            for iter, data in enumerate(t):
                if torch.cuda.is_available():
                    for i in range(len(data)):
                        try:
                            data[i] = data[i].cuda()
                        except:
                            pass
                subject_label = data[-1]
                label = data[-2]
                args = data[0:2]
                logits, subject_label_logits, attx = self.parallel_model(*args)
                loss = self.loss_func(logits, label)

                if self.add_subject_loss:
                    subject_loss = self.subject_loss(subject_label_logits.transpose(1, 2), subject_label)
                    loss += subject_loss

                l = list(logits.detach().cpu().numpy())
                # self.metric.eval(l, self.train_loader.dataset.data[data_idx:data_idx + len(l)])
                data_idx += len(l)

                avg_loss.update(loss.item(), 1)

                t.set_postfix(loss=avg_loss.avg)
                # Optimize
                if warmup == True:
                    warmup_step = 300
                    if global_step < warmup_step:
                        warmup_rate = float(global_step) / warmup_step
                    else:
                        warmup_rate = 1.0
                    for param_group in self.optimizer.param_groups:
                        param_group['lr'] = self.lr * warmup_rate
                loss.backward()
                self.optimizer.step()
                self.optimizer.zero_grad()
                global_step += 1
            # Val 
            print("=== Epoch %d val ===" % epoch)
            if self.val_loader is not None:
                result = self.eval_model(self.val_loader)
                if result[metric] > best_metric:
                    print("Best ckpt and saved.")
                    folder_path = '/'.join(self.ckpt.split('/')[:-1])
                    if not os.path.exists(folder_path):
                        os.mkdir(folder_path)
                    # torch.save({'state_dict': self.model.state_dict()}, self.ckpt)
                    torch.save(self.parallel_model, self.ckpt)
                    best_metric = result[metric]
            else:
                torch.save(self.parallel_model, self.ckpt)
        print("Best %s on val set: %f" % (metric, best_metric))

    def eval_model(self, eval_loader):
        self.eval()
        from tqdm import tqdm
        tqdm = partial(tqdm, position=0, leave=False)
        # avg_acc = AverageMeter()
        self.metric.reset()
        data_idx = 0
        with torch.no_grad():
            t = tqdm(eval_loader, leave=False)
            for iter, data in enumerate(t):
                if torch.cuda.is_available():
                    for i in range(len(data)):
                        try:
                            data[i] = data[i].cuda()
                        except:
                            pass
                label = data[-1]
                args = data[0:2]
                logits, _, attx = self.parallel_model(*args)
                l = list(logits.cpu().numpy())
                self.metric.eval(l, eval_loader.dataset.data[data_idx:data_idx + len(l)])
                data_idx += len(l)

                t.set_postfix(f1=self.metric.get_result()["without_na_micro_f1"])
        print(self.metric.get_result())
        return self.metric.get_result()


    def eval_model_few_shot(self, test_loader, K, Q, iter):
      # Find the indices for each class
      test_dataset = test_loader.dataset
      collection = {}
      for i, data in enumerate(test_dataset.data):
        if data['relation'] not in collection.keys():
          collection[data['relation']] = [i]
        else:
          collection[data['relation']].append(i)

      # from tqdm import tqdm
      # tqdm = partial(tqdm, position=0, leave=False)
      self.metric.reset()
      # t = tqdm(range(iter), leave=False)
      for _ in range(iter):
        # Pick K + Q samples from each class
        indices = {}
        for label_class in collection:
          indices[label_class] = np.random.choice(
                          list(range(len(collection[label_class]))), K + Q, False)
        # self.parallel_model.load_state_dict(torch.load(checkpoint).state_dict())
        # Training for K samples
        self.train()
        for i in range(K):
          for label_class in indices:
            data = test_dataset.__getitem__(indices[label_class][i])
            data_cuda = []
            for item in data:
              data_cuda.append(item.cuda())
            label = data_cuda[-2]
            args = data_cuda[0:2]
            logits, subject_label_logits, attx = self.parallel_model(*args)
            loss = self.loss_func(logits, label)
            loss.backward()
            self.optimizer.step()
            self.optimizer.zero_grad()
        # Test on Q samples
        self.eval()
        with torch.no_grad():
          for i in range(K, K+Q):
            for label_class in indices:
              data = test_dataset.__getitem__(indices[label_class][i])
              data_cuda = []
              for item in data:
                data_cuda.append(item.cuda())
              label = torch.unsqueeze(data_cuda[-1], 0)
              args = data_cuda[0:2]
              logits, subject_label_logits, attx = self.parallel_model(*args)
              l = list(logits.cpu().numpy())
              self.metric.eval(l, [test_dataset.data[indices[label_class][i]]])

              # t.set_postfix(f1=self.metric.get_result()["without_na_micro_f1"])
      # print(self.metric.get_result())
      return self.metric.get_result()

    def load_state_dict(self, state_dict):
        self.model.load_state_dict(state_dict)
